version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: tradecaptain_postgres
    environment:
      POSTGRES_DB: tradecaptain
      POSTGRES_USER: tradecaptain_user
      POSTGRES_PASSWORD: tradecaptain_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tradecaptain_network

  # QuestDB (6.5x faster than TimescaleDB for time-series data)
  questdb:
    image: questdb/questdb:latest
    container_name: tradecaptain_questdb
    ports:
      - "9000:9000"    # Web Console
      - "8812:8812"    # PostgreSQL wire protocol
      - "9009:9009"    # InfluxDB line protocol (high-speed ingestion)
    volumes:
      - questdb_data:/var/lib/questdb
      - ./database/questdb_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - QDB_CAIRO_SQL_COPY_ROOT=/var/lib/questdb/public
      - QDB_PG_USER=tradecaptain_user
      - QDB_PG_PASSWORD=tradecaptain_pass
      - QDB_PG_READONLY_USER_ENABLED=false
    networks:
      - tradecaptain_network

  # TimescaleDB (kept for migration period - will be removed)
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: tradecaptain_timescaledb_legacy
    environment:
      POSTGRES_DB: timeseries_data
      POSTGRES_USER: timescale_user
      POSTGRES_PASSWORD: timescale_pass
    ports:
      - "5433:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./database/timescale_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tradecaptain_network
    profiles:
      - migration  # Only start during migration

  # ClickHouse (100x faster analytical queries)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: tradecaptain_clickhouse
    ports:
      - "8123:8123"    # HTTP interface
      - "9001:9000"    # Native client
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./database/clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - CLICKHOUSE_DB=tradecaptain_analytics
      - CLICKHOUSE_USER=tradecaptain_user
      - CLICKHOUSE_PASSWORD=tradecaptain_pass
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    networks:
      - tradecaptain_network

  # Dragonfly Cache (25x faster than Redis)
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: tradecaptain_dragonfly
    command: >
      --cluster_mode=emulated
      --port=6379
      --save_schedule="0 0 * * * *"
      --maxmemory=2gb
    ports:
      - "6379:6379"
    volumes:
      - dragonfly_data:/data
    networks:
      - tradecaptain_network
    deploy:
      resources:
        limits:
          memory: 2G

  # Benthos (Go-native stream processing)
  benthos:
    image: jeffail/benthos:latest
    container_name: tradecaptain_benthos
    volumes:
      - ./infrastructure/benthos/config.yaml:/benthos.yaml
      - ./infrastructure/benthos/pipelines:/pipelines
    depends_on:
      - kafka
      - questdb
      - clickhouse
    networks:
      - tradecaptain_network
    command: -c /benthos.yaml

  # Kafka (for real-time data streaming)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: tradecaptain_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - tradecaptain_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: tradecaptain_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - tradecaptain_network

  # Data Collector Service
  data-collector:
    build:
      context: ./services/data-collector
      dockerfile: Dockerfile
    container_name: tradecaptain_data_collector
    depends_on:
      - postgres
      - dragonfly
      - kafka
    environment:
      - DATABASE_URL=postgres://tradecaptain_user:tradecaptain_pass@postgres:5432/tradecaptain?sslmode=disable
      - REDIS_URL=redis://dragonfly:6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    env_file:
      - .env
    networks:
      - tradecaptain_network
    restart: unless-stopped

  # Calculation Engine Service
  calculation-engine:
    build:
      context: ./services/calculation-engine
      dockerfile: Dockerfile
    container_name: tradecaptain_calc_engine
    depends_on:
      - dragonfly
    environment:
      - REDIS_URL=redis://dragonfly:6379
    networks:
      - tradecaptain_network
    restart: unless-stopped

  # API Gateway Service
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: tradecaptain_api_gateway
    depends_on:
      - postgres
      - dragonfly
      - kafka
      - data-collector
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://tradecaptain_user:tradecaptain_pass@postgres:5432/tradecaptain?sslmode=disable
      - REDIS_URL=redis://dragonfly:6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_SECRET=your-jwt-secret-key
      - PORT=8080
    env_file:
      - .env
    networks:
      - tradecaptain_network
    restart: unless-stopped

  # Frontend (React App)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tradecaptain_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_WS_URL=ws://localhost:8080
    networks:
      - tradecaptain_network

  # Nginx (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: tradecaptain_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - api-gateway
    networks:
      - tradecaptain_network

  # Monitoring with Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: tradecaptain_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/grafana:/etc/grafana/provisioning
    networks:
      - tradecaptain_network

  # Prometheus (Metrics Collection)
  prometheus:
    image: prom/prometheus:latest
    container_name: tradecaptain_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - tradecaptain_network

  # Grafana Phlare (Continuous Profiling)
  phlare:
    image: grafana/phlare:latest
    container_name: tradecaptain_phlare
    ports:
      - "4100:4100"
    volumes:
      - phlare_data:/data
      - ./infrastructure/phlare/config.yaml:/etc/phlare/config.yaml
    command: -config.file=/etc/phlare/config.yaml
    networks:
      - tradecaptain_network

volumes:
  postgres_data:
  timescaledb_data:
  questdb_data:
  clickhouse_data:
  dragonfly_data:
  grafana_data:
  prometheus_data:
  phlare_data:

networks:
  tradecaptain_network:
    driver: bridge